package com.whatsflow.ai.spi;


public enum AICapability {
    CHAT, RAG_CHAT, SUMMARIZE, SUGGEST, INTENT, SENTIMENT, LANGUAGE, TRANSLATE,
    FAQ, DOC_CHAT, RECOMMEND, LEAD_SCORE, COPYWRITE, CAPTION, REPORT, EMBED
}
